os: osx

language:

script:
    - find . -type f
    - find . -type f -name maketestfiles.sh
    - cd raster-sample-files
    - echo "$(ls -l /usr/libexec/cups/filter)"
    - ./maketestfiles.sh help
      #- ./maketestfiles.sh all pstoraster apple
      #- ./maketestfiles.sh all pstoraster pwg
      #- ./maketestfiles.sh all pstoraster ras
    - ./maketestfiles.sh all cgpdftoraster apple
    - ./maketestfiles.sh all cgpdftoraster pwg
    - ./maketestfiles.sh all cgpdftoraster ras
      #- ./maketestfiles.sh all cgimagetoraster apple
      #- ./maketestfiles.sh all cgimagetoraster pwg
      #- ./maketestfiles.sh all cgimagetoraster ras
    - for i in *.apple *.ras *.pwg ; do gzip $i ; done
    - find . -type f -name "*.ras"
    - find . -type f -name "*.apple"
    - find . -type f -name "*.pwg"
    - find . -type f -name "*.log"
    - file *.ras
    - file *.apple
    - file *.pwg
    - file *.log
    - for i in *.apple *.ras *.pwg ; do gzip $i ; done
    - for i in $(ls -1 *.apple | head -n 1) ; do gunzip $i ; done
    - for i in $(ls -1 *.ras | tail -n 1) ; do gunzip $i ; done
    - for i in $(ls -1 *.pwg | tail -n 5 | head -n 1) ; do gunzip $i ; done
    - rm -rf *.log
    - cd ..
    - COPYFILE_DISABLE=1 tar cvzf raster-sample-files.tar.gz raster-sample-files/
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - bash upload.sh rasterview-sample-files.tar.gz

after_success:
  # Do nothing for now
