os: osx

script:
    - cd rasterview-sample-files
    - echo $(ls -l /usr/libexec/cups/filter)
    - ./maketestfiles.sh all help
    #- ./maketestfiles.sh all pstoraster apple
    #- ./maketestfiles.sh all pstoraster pwg
    #- ./maketestfiles.sh all pstoraster ras
    - ./maketestfiles.sh all cgpdftoraster apple
    - ./maketestfiles.sh all cgpdftoraster pwg
    - ./maketestfiles.sh all cgpdftoraster ras
    #- ./maketestfiles.sh all cgimagetoraster apple
    #- ./maketestfiles.sh all cgimagetoraster pwg
    #- ./maketestfiles.sh all cgimagetoraster ras
    - for i in *.apple *.ras *.pwg ; do gzip $i ; done
    - find . -type f -name "*.ras"
    - find . -type f -name "*.apple"
    - find . -type f -name "*.pwg"
    - find . -type f -name "*.log"
    - rm -rf *.log
    - cd ..
    - tar cvzf rasterview-sample-files.tar.gz rasterview-sample-files/
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - bash upload.sh rasterview-sample-files.tar.gz

after_success:
  # Do nothing for now
