os: osx

language:

script:

      # What is our Travis environment?
    - env | grep -i travis

      # Which OS are we on?
    - uname -a
    - sw_vers
    - system_profiler SPSoftwareDataType
    - df -h
    - mount

      # What files are here?
    - find . -not -iwholename '.git' -type f
    - find . -not -iwholename '.git' -type f -name maketestfiles.sh
    - cd raster-sample-files

      # Which CUPS filters are we equipped with?
    - ls -l /usr/libexec/cups/filter

      # What are our MIME type and conversion definitions?
    - for i in /usr/share/cups/mime/*.convs ; do echo $i ; cat $i ; echo ; done
    - for i in /usr/share/cups/mime/*.types ; do echo $i ; cat $i ; echo ; done

      # Does maketestfiles.sh work?
    - ./maketestfiles.sh help
    - ./maketestfiles.sh all pstoraster apple
    - ./maketestfiles.sh all pstoraster pwg
    - ./maketestfiles.sh all pstoraster ras
    - ./maketestfiles.sh all cgpdftoraster apple
    - ./maketestfiles.sh all cgpdftoraster pwg
    - ./maketestfiles.sh all cgpdftoraster ras
    - ./maketestfiles.sh all cgimagetoraster apple
    - ./maketestfiles.sh all cgimagetoraster pwg
    - ./maketestfiles.sh all cgimagetoraster ras

      # Which and how many raster files have we produced?
    - find . -type f -name "*.ras"   | tail -n 10
    - find . -type f -name "*.apple" | tail -n 10
    - find . -type f -name "*.pwg"   | tail -n 10
    - find . -type f -name "*.log"   | tail -n 10

      # How many of each?
    - find . -type f -name "*.log"   | wc -l
    - find . -type f -name "*.apple" | wc -l
    - find . -type f -name "*.pwg"   | wc -l
    - find . -type f -name "*.ras"   | wc -l

      # How much disk space does that need?
    - du -hsc *.ras                     | tail -n 1
    - du -hsc       *.apple             | tail -n 1
    - du -hsc               *.pwg       | tail -n 1
    - du -hsc                     *.log | tail -n 1
    - du -hsc *.ras *.apple *.pwg *.log | tail -n 1

      # Can 'file' determine what these are?
    - file *.ras   | head -n 10
    - file *.apple | head -n 10
    - file *.pwg   | head -n 10
    - file *.log   | head -n 10

      # Compress all raster files:
    - for i in *.apple *.ras *.pwg ; do gzip $i ; done

      # How much disk space now?
    - du -hsc *.ras.gz                     | tail -n 1
    - du -hsc          *.apple.gz          | tail -n 1
    - du -hsc                     *.pwg.gz | tail -n 1
    - du -hsc *.ras.gz *.apple.gz *.pwg.gz | tail -n 1

      # Uncompress 3 random files again, one of each type:
    - for i in $(ls -1 *.apple.gz | grep -v FAILED | head -n 1) ; do gunzip $i ; done
    - for i in $(ls -1 *.ras.gz   | grep -v FAILED | tail -n 1) ; do gunzip $i ; done
    - for i in $(ls -1 *.pwg.gz   | grep -v FAILED | tail -n 5 | head -n 1) ; do gunzip $i ; done

      # Set up a VERSION string:
    - VERSION=$TRAVIS_BUILD_NUMBER-$(date "+%Y%m%d")

      # Make subdirs for each type (and logs) and move types there:
    - mkdir  failed-convfiles failed-convlogs success-convlogs apple-raster pwg-raster cups-raster
    - mv *-FAILED.{apple,pwg,ras}     failed-convfiles/   || echo "No files: \*-FAILED.{apple,pwg,ras}"
    - mv *-FAILED.log                 failed-convlogs/    || echo "No files: \*-FAILED.log"
    - mv *-SUCCESS.log                success-convlogs/   || echo "No files: \*-SUCCESS.log"
    - mv *.apple *.apple.gz           apple-raster/       || echo "No files: \*.apple \*.apple.gz"
    - mv *.pwg   *.pwg.gz             pwg-raster/         || echo "No files: \*.pwg   \*.pwg.gz"
    - mv *.ras   *.ras.gz             cups-raster/        || echo "No files: \*.ras   \*.ras.gz"

      # Make tarball for each subdir:
    - COPYFILE_DISABLE=1  tar cvzf      failed-convfiles-$VERSION.tar.gz  failed-convfiles/
    - COPYFILE_DISABLE=1  tar cvzf       failed-convlogs-$VERSION.tar.gz  failed-convlogs/
    - COPYFILE_DISABLE=1  tar cvzf      success-convlogs-$VERSION.tar.gz  success-convlogs/
    - COPYFILE_DISABLE=1  tar cvzf  apple-raster-samples-$VERSION.tar.gz  apple-raster/
    - COPYFILE_DISABLE=1  tar cvzf    pwg-raster-samples-$VERSION.tar.gz  pwg-raster/
    - COPYFILE_DISABLE=1  tar cvzf   cups-raster-samples-$VERSION.tar.gz  cups-raster/

      # Remove subdirs again, clean up for final tarball:
    - rm -rf failed-convfiles/ failed-convlogs/ success-convlogs/ apple-raster/ pwg-raster/ cups-raster/
    - ls -lh *-$VERSION.tar.gz

      # Create the final tarball:
    - cd ..
    - du -hsc raster-sample-files
    - COPYFILE_DISABLE=1 tar cvzf raster-sample-files-$VERSION.tar.gz raster-sample-files/
    - du -hsc raster-sample-files-$VERSION.tar.gz

      # Upload the results:
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - bash upload.sh raster-sample-files-$VERSION.tar.gz

      # Any changes in our Travis environment?
    - env | grep -i travis

after_success:
  # Do nothing for now
